### ISSUE TITLE
tslib_1.__spreadArray is not a function

### ISSUE THREAD

**Issue by ArvindhMangoleap** [Shopify/shopify-api-node#443]
I am getting this error `tslib_1.__spreadArray is not a function`

at new AuthScopes (...\@shopify\shopify-api\dist\auth\scopes\index.js:20:49)
    at Object.<anonymous> (...\@shopify\shopify-api\dist\context.js:14:13)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)  
    at Module._compile (...\source-map-support\source-map-support.js:547:25)
    at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.nodeDevHook [as .js] (...\ts-node-dev\lib\hook.js:63:13)
    at Module.load (internal/modules/cjs/loader.js:928:32)       
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)    
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (...\@shopify\shopify-api\dist\index.js:5:17)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)  
    at Module._compile (...\source-map-support\source-map-support.js:547:25)
    at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.nodeDevHook [as .js] (...\ts-node-dev\lib\hook.js:63:13)
    at Module.load (internal/modules/cjs/loader.js:928:32)       
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)    
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (...\packages\server\src\app\modules\integration\shopify\shopify.service.ts:1:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)  
    at Module._compile (...\source-map-support\source-map-support.js:547:25)
    at Module.m._compile (C:\Users\User\AppData\Local\Temp\ts-node-dev-hook-48656411659554966.js:69:33)
    at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at require.extensions.<computed> (C:\Users\User\AppData\Local\Temp\ts-node-dev-hook-48656411659554966.js:71:20)
    at Object.nodeDevHook [as .ts] (...\ts-node-dev\lib\hook.js:63:13)
    at Module.load (internal/modules/cjs/loader.js:928:32)       
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)

typescript  version ^4.6.3
 @shopify/shopify-api  version ^4.2.0

**Comment by MurmeltierS** [comment]
experiencing the same error on Nuxt 3
