### ISSUE TITLE
Unexpected behavior when performing Shopify Billing check 

### ISSUE THREAD

**Issue by coolcomfort** [Shopify/shopify-api-node#519]
# Issue summary

I have set up the shopify api for installing an app, but when trying to set up billing there is an unexpected GraphQL error. I have set up billing within the context with correct types, then also used the same Shopify.Billing.check code provided from docs. 

## Expected behavior

After installing the app, the Shopify.Billing.check code should return the user to either a confirm billing page or the frontend redirect route. 

## Actual behavior

Chrome says "localhost refused to connect" and a graphQL error is in the terminal.

```js
const {hasPayment, confirmBillingUrl} = await Shopify.Billing.check({
    session,
    isTest: true,
  });

  console.log(hasPayment, confirmBillingUrl);


  if (!hasPayment) {
    return redirect(confirmBillingUrl);
  }
```

```
        var _this = _super.apply(this, tslib_1.__spreadArray([], tslib_1.__read(args), false)) || this;
                           ^

GraphqlQueryError: GraphQL query returned errors
    at GraphqlQueryError.ShopifyError [as constructor] (/Users/name/Documents/repos/shopify-api-2/node_modules/@shopify/shopify-api/dist/error.js:13:28)
    at new GraphqlQueryError (/Users/name/Documents/repos/shopify-api-2/node_modules/@shopify/shopify-api/dist/error.js:156:28)
    at GraphqlClient.<anonymous> (/Users/name/Documents/repos/shopify-api-2/node_modules/@shopify/shopify-api/dist/clients/graphql/graphql_client.js:43:35)
    at step (/Users/name/Documents/repos/shopify-api-2/node_modules/tslib/tslib.js:144:27)
    at Object.next (/Users/name/Documents/repos/shopify-api-2/node_modules/tslib/tslib.js:125:57)
    at fulfilled (/Users/name/Documents/repos/shopify-api-2/node_modules/tslib/tslib.js:115:62)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  response: {
    errors: [
      {
        message: "Field 'endCursor' doesn't exist on type 'PageInfo'",
        locations: [ { line: 14, column: 11 } ],
        path: [
          'query appPurchases',
          'currentAppInstallation',
          'oneTimePurchases',
          'pageInfo',
          'endCursor'
        ],
        extensions: {
          code: 'undefinedField',
          typeName: 'PageInfo',
          fieldName: 'endCursor'
        }
      }
    ]
  }
}
```

## Steps to reproduce the problem

1. Follow documentation to create login, OAuth, and success route. 
2. Implement billing in context. Ensure all names are the correct type (interval is enum)

```js
  BILLING: {
    chargeName: 'Test Charge',
    amount: 10,
    currencyCode: 'USD',
    interval: 'Every30Days'
  }
```

3. Attempt to run Shopify.Billing.check in an area where session is obtainable, after app is successfully installed (billing requires a session to access the API)

```js
const {hasPayment, confirmBillingUrl} = await Shopify.Billing.check({
    session,
    isTest: true,
  });

  console.log(hasPayment, confirmBillingUrl);


  if (!hasPayment) {
    return redirect(confirmBillingUrl);
  }
```

**Comment by coolcomfort** [comment]
Hello, I am using 5.1.0, which billing was just added to iirc.

**Comment by coolcomfort** [comment]
Thanks, that seemed to solve it.
